from .network import RPI_HOST, GODOT_HOST, PORT
from .configs import LINE_FOLLOWER_CONFIG, SONAR_CONFIG, MOTOR_CONFIG, OBSTACLE_AVOIDANCE_CONFIG
from .obstacle import OBSTACLE_DETECTED_DISTANCE, TURN_ANGLE_1, TURN_ANGLE_2, TURN_ANGLE_3, STRAIGHT_DISTANCE_1, STRAIGHT_DISTANCE_2, STRAIGHT_DISTANCE_3